M48
; DRILL file {KiCad 8.0.5} date 2024-11-16T15:57:53-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-16T15:57:53-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.740
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X32.241Y-108.316
T2
X32.241Y-50.316
X81.241Y-50.316
X81.241Y-108.316
M30
